const app = document.getElementById('app')
const gameContainer = document.createElement('div')
const playerSelection = document.createElement('div')
const gameBoard = document.createElement('div')
const playerX = document.createElement('div')
const xSecondArm = document.createElement('div')
const playerY = document.createElement('div')

gameContainer.classList.add('game')
playerSelection.classList.add('game__player-selection')
gameBoard.classList.add('game__game-board')
playerX.classList.add('player-selection__player-x')
xSecondArm.classList.add('x-second-arm')
playerY.classList.add('player-selection__player-y')

app.appendChild(gameContainer)
gameContainer.appendChild(playerSelection)
gameContainer.appendChild(gameBoard)
playerSelection.appendChild(playerX)
playerSelection.appendChild(playerY)
playerX.appendChild(xSecondArm)
